#!/bin/sh
# ***********************************
# Special build configuration defines
# ***********************************
# CFG=(relese|debug)
# CFG_LINK=(dynamic|static)
# OBJS - specify test program object file (sqltest.obj by default)
# ***********************************

SA_OPTIONS="SA_TOOLCHAIN_PREFIX=i686-w64-mingw32-"

make -f Makefile.mingw-tool CFG=release CFG_LINK=dynamic $SA_OPTIONS safe_clean all
make -f Makefile.mingw-tool CFG=release CFG_LINK=static $SA_OPTIONS safe_clean all

make -f Makefile.mingw-tool CFG=debug CFG_LINK=dynamic $SA_OPTIONS safe_clean all
make -f Makefile.mingw-tool CFG=debug CFG_LINK=static $SA_OPTIONS safe_clean all
